FROM node:16-slim

# Import envs mentioned in .env file mounted by compose file.
ARG USER_PORT
ARG AUTH_PORT
ARG POST_PORT
ARG CATEGORY_PORT

# Installs OS dependencies
RUN apt update
RUN apt install -y libssl-dev #required for prisma binaries

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy both package files, use npm ci if you have lock file.
COPY package*.json ./
RUN npm ci

# Copy code and build
COPY . ./

# Expose API port
EXPOSE $USER_PORT $AUTH_PORT $POST_PORT $CATEGORY_PORT