FROM node:16-slim

RUN apt update

#installs openssl, required for prisma binaries
RUN apt install -y libssl-dev

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install dependencies.
# If you add a package-lock.json speed your build by switching to 'npm ci'.
RUN npm ci --only=production

# Copy local code to the container image.
COPY . .

# Expose API port
EXPOSE 3000 3001 3002 3003