version: "3.0"

services:
  app:
    image: "node:14-slim"
    container_name: 'server'
    build:
      context: .
      dockerfile: Dockerfile.slim
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "${USER_PORT}:${USER_PORT}"
      - "${AUTH_PORT}:${AUTH_PORT}"
    tty: true
    networks:
      - nest-network
    entrypoint: [ "/bin/sh","-c" ]
    command:
    - |
      npm ci
      npx prisma generate
      npm run migrate:dev
      npm run start:dev
  database-mysql:
    image: mysql:5.7
    restart: always
    networks:
      - nest-network
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - datastore:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database-mysql
    image: phpmyadmin
    restart: always
    ports:
      - '3308:80'
    environment:
      PMA_HOST: database-mysql
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - nest-network

volumes:
  datastore:
networks:
  nest-network: